# ==============================================================================
# Affinidi Trust Fabric - Makefile
# ==============================================================================
SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c
#
# This Makefile provides convenient shortcuts for common development tasks.
# Run `make help` for a list of available commands.
#
# Prerequisites:
# - Rust 1.95.0+ with cargo
# - Node.js and npm (for frontend)
# - Docker (for containerized deployment)
# - jq (for some storage operations)
# - mdbook (for documentation)
# ==============================================================================

.PHONY: help cargo-release cargo-build run-debug run-watch run-release \
        config-certs config-debug config-debug-dev config-debug-x config-test config-release install-deps install-rust-deps verify-rust-deps install-git-hooks setup-vscode \
        docker-build-local docker-build-local-dev docker-rebuild-local docker-rebuild-local-dev docker-run docker-run-dev docker-shell docker-network \
        config-docker \
	test test-unit test-bins test-policies test-coverage test-junit test-rust-ci npm-test npm-test-ci npm-build npm-build-ci npm-install npm-install-ci clippy clippy-ci fmt fmt-www-all fmt-check lint npm-lint shellcheck npm-lint-www-all npm-lint-ci check cargo-build-ci node-ci rust-ci node-local rust-local local audit-www-all audit-fix-www-all browserslist-update license-check \
        www www-dev \
        clean clean-all clear-storage clear-storage-local \
		demo-multi-tenancy \
        generate-cert trust-cert derive-x402-addresses \
        ngrok pre-commit pre-commit-rust pre-commit-node dev full-setup release \
        ui-test ui-test-headed ui-test-report \
		itest-a2a itest-a2a-setup itest-a2a-run itest-a2a-teardown itest-a2a-clean itest-a2a-shopping \
		gw-e2e mcp-conformance mcp-conformance-legacy \
		mediator mediator-start mediator-up mediator-stop mediator-down

# Default target
.DEFAULT_GOAL := help

# Colors for terminal output
BLUE := $(shell printf '\033[0;34m')
GREEN := $(shell printf '\033[0;32m')
YELLOW := $(shell printf '\033[1;33m')
RED := $(shell printf '\033[0;31m')
NC := $(shell printf '\033[0m')

RUST_LLVM_MAJOR := $(shell rustc -vV 2>/dev/null | sed -n 's/^LLVM version: \([0-9][0-9]*\).*/\1/p')
RUST_LLVM_PREFIX := $(firstword $(wildcard /opt/homebrew/opt/llvm@$(RUST_LLVM_MAJOR) /usr/local/opt/llvm@$(RUST_LLVM_MAJOR)))
RUST_LLVM_DEPS := $(if $(RUST_LLVM_MAJOR),llvm@$(RUST_LLVM_MAJOR),llvm)
RUST_DEPS := sccache keith/formulae/ld64.lld protobuf xmlsec1 cmake libxml2 $(RUST_LLVM_DEPS)
CARGO_TOOLS := cargo-llvm-cov cargo-nextest cargo-audit cargo-deny cargo-watch
DEPS := jq mdbook plantuml pre-commit gitleaks
COVERAGE_THRESHOLD ?= 37
WWW_DIR ?= www/default
WWW_DIRS := www/default
AZURE_TENANT ?=
RUST_LOG ?= debug
# Hex pepper (>=32 bytes) for stable credential-derived agent DIDs
# (from_mtls / from_api_key / static / from_jwt_claim) across restarts. Defaults
# to the file generated by `config-certs` (envs/identity_hash_pepper), so local
# DIDs are stable across restarts and shared across local instances. Override via
# env or `make run-debug AG_IDENTITY_HASH_PEPPER=$$(openssl rand -hex 32)`. Empty
# (no file, explicit empty) = ephemeral pepper (DIDs reset on restart).
AG_IDENTITY_PEPPER_FILE ?= envs/identity_hash_pepper
AG_IDENTITY_HASH_PEPPER ?= $(shell cat $(AG_IDENTITY_PEPPER_FILE) 2>/dev/null)
# Hex backup encryption key (32 bytes). Required at runtime; defaults to the file
# generated by `config-certs` (envs/backup_encryption_key) so local backups/restores
# work out of the box. Override via env or `make run-debug AG_BACKUP_ENCRYPTION_KEY=$$(openssl rand -hex 32)`.
AG_BACKUP_KEY_FILE ?= envs/backup_encryption_key
AG_BACKUP_ENCRYPTION_KEY ?= $(shell cat $(AG_BACKUP_KEY_FILE) 2>/dev/null)
LLVM_COV ?= $(if $(RUST_LLVM_PREFIX),$(RUST_LLVM_PREFIX)/bin/llvm-cov,$(shell command -v llvm-cov 2>/dev/null))
LLVM_PROFDATA ?= $(if $(RUST_LLVM_PREFIX),$(RUST_LLVM_PREFIX)/bin/llvm-profdata,$(shell command -v llvm-profdata 2>/dev/null))
LLVM_COV_ENV := $(if $(LLVM_COV),LLVM_COV="$(LLVM_COV)") $(if $(LLVM_PROFDATA),LLVM_PROFDATA="$(LLVM_PROFDATA)")
COVERAGE_PROFILE_ARTIFACTS := target/llvm-cov-target/*.profraw target/llvm-cov-target/*-profraw-list target/llvm-cov-target/*.profdata

# ==============================================================================
# Help
# ==============================================================================

help: ## Show this help message
	@echo ""
	@echo "$(BLUE)Affinidi Trust Fabric - Available Commands$(NC)"
	@echo "=============================================="
	@echo ""
	@awk 'BEGIN {FS = ":.*##"} /^[a-zA-Z0-9_-]+:.*##/ { printf "  $(GREEN)%-20s$(NC) %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
	@echo ""

# ==============================================================================
# Setup Commands
# ==============================================================================

install-rust-deps: ## Install Rust build toolchain dependencies (sccache, lld, etc.)
	@echo "$(BLUE)📦 Installing Rust build dependencies...$(NC)"
	@brew install $(RUST_DEPS) 2>/dev/null || true
	@rustup component add llvm-tools-preview
	@for tool in $(CARGO_TOOLS); do cargo install $$tool --locked; done
	@echo "$(GREEN)✅ Rust dependencies installed!$(NC)"

verify-rust-deps: ## Verify Rust build toolchain dependencies (sccache, lld, etc.)
	@echo "$(BLUE)📦 Verifying Rust build dependencies...$(NC)"
	@brew ls --version $(RUST_DEPS) 2>/dev/null || (echo "$(RED)❌ Rust dependencies are not installed. Please run 'make install-rust-deps' to install them.$(NC)" && exit 1)
	@for tool in $(CARGO_TOOLS); do \
		command -v $$tool >/dev/null 2>&1 || (echo "$(RED)❌ $$tool not found. Please run 'make install-rust-deps' to install it.$(NC)" && exit 1); \
	done
	@rustup component list --installed 2>/dev/null | grep -q llvm-tools || (echo "$(RED)❌ llvm-tools-preview not installed. Please run 'make install-rust-deps'.$(NC)" && exit 1)
	@echo "$(GREEN)✅ Rust dependencies verified!$(NC)"

install-git-hooks: ## Install git hooks via pre-commit framework
	@echo "$(BLUE)🔗 Installing git hooks...$(NC)"
	@pre-commit install
	@echo "$(GREEN)✅ Git hooks installed!$(NC)"

install-deps: install-rust-deps ## Install all local development dependencies (macOS)
	@echo "$(BLUE)📦 Installing dependencies...$(NC)"
	@brew install $(DEPS) 2>/dev/null || true
	@$(MAKE) install-git-hooks
	@echo "$(GREEN)✅ Dependencies installed!$(NC)"

# ==============================================================================
# Build Commands
# ==============================================================================

cargo-build: verify-rust-deps ## Build the debug binary
	@echo "$(BLUE)📦 Building debug binary...$(NC)"
	@cargo build
	@echo "$(GREEN)✅ Debug build completed!$(NC)"

cargo-build-ci: ## Build all Rust targets/features like the CI build
	@echo "$(BLUE)📦 Building all Rust targets and features...$(NC)"
	@cargo build --all-targets --all-features
	@echo "$(GREEN)✅ CI-equivalent Rust build completed!$(NC)"

cargo-release: verify-rust-deps ## Build the release binary
	@echo "$(BLUE)📦 Building release binary...$(NC)"
	@cargo build --release
	@echo "$(GREEN)✅ Release build completed!$(NC)"

npm-install: ## Install frontend npm dependencies
	@echo "$(BLUE)📦 Installing npm dependencies...$(NC)"
	@cd $(WWW_DIR) && npm install
	@echo "$(GREEN)✅ npm install completed!$(NC)"

npm-install-ci: ## Install frontend npm dependencies (npm ci)
	@echo "$(BLUE)📦 Installing npm dependencies with npm ci...$(NC)"
	@cd $(WWW_DIR) && npm ci
	@echo "$(GREEN)✅ npm ci completed!$(NC)"

www: ## Build the frontend app
	@echo "$(BLUE)📦 Building frontend app...$(NC)"
	@./$(WWW_DIR)/build.sh
	@echo "$(GREEN)✅ Dashboard build completed!$(NC)"

www-rebuild: ## Delete $(WWW_DIR)/build, rebuild UI, and refresh local env config
	@echo "$(BLUE)🗑️  Removing $(WWW_DIR)/build...$(NC)"
	@rm -rf $(WWW_DIR)/build
	@echo "$(BLUE)📦 Rebuilding frontend app...$(NC)"
	@./$(WWW_DIR)/build.sh
	@echo "$(BLUE)🔧 Refreshing local env config with new build path...$(NC)"
	@./scripts/_prepare.sh debug envs/local
	@echo "$(GREEN)✅ UI rebuilt and local env updated!$(NC)"

# ==============================================================================
# Config Commands
# ==============================================================================

config-certs: ## Prepare TLS certificates and local identity pepper for development
	@echo "$(BLUE)🔐 Setting up TLS certificates...$(NC)"
	@AG_IDENTITY_PEPPER_FILE="$(AG_IDENTITY_PEPPER_FILE)" AG_BACKUP_KEY_FILE="$(AG_BACKUP_KEY_FILE)" ./scripts/_certs.sh
	@echo "$(GREEN)✅ TLS certificates ready!$(NC)"

config-debug: config-certs www ## Full debug environment setup (deps + build + config)
	@echo "$(BLUE)🔧 Configuring debug environment...$(NC)"
	@./scripts/_prepare.sh debug envs/local
	@echo "$(GREEN)✅ Debug environment ready!$(NC)"

config-debug-dev: config-certs ## Debug environment setup without static frontend build (for dev server)
	@echo "$(BLUE)🔧 Configuring debug environment (dev mode)...$(NC)"
	@./scripts/_prepare.sh debug envs/local
	@echo "$(GREEN)✅ Debug dev environment ready!$(NC)"

config-debug-x: config-certs www ## Debug setup for a specific instance (x=1, x=my-tests, etc.)
	@echo "$(BLUE)🔧 Configuring debug instance $(or $(x),1)...$(NC)"
	@./scripts/_prepare.sh debug envs/local-$(or $(x),1)
	@echo "$(GREEN)✅ Debug instance $(or $(x),1) ready!$(NC)"

config-release: config-certs www cargo-release ## Full release environment setup (deps + build + config)
	@echo "$(BLUE)🔧 Configuring release environment...$(NC)"
	@./scripts/_prepare.sh release envs/local
	@echo "$(GREEN)✅ Release environment ready!$(NC)"

config-docker: config-certs ## Docker environment setup
	@echo "$(BLUE)🔧 Configuring Docker environment...$(NC)"
	@./scripts/_prepare.sh docker envs/docker
	@echo "$(GREEN)✅ Docker environment ready!$(NC)"

setup-vscode: config-certs ## Generate VS Code CodeLLDB debug config under .vscode/ (gitignored)
	@echo "$(BLUE)🔧 Generating VS Code debug configuration...$(NC)"
	@./scripts/setup-vscode.sh
	@echo "$(GREEN)✅ VS Code debug configuration ready!$(NC)"

config-test: config-certs ## Prepare the certs and keys the test targets need
	@echo "$(BLUE)🔧 Configuring test environment...$(NC)"
	@echo "$(GREEN)✅ Test environment ready!$(NC)"

# ==============================================================================
# Run Commands
# ==============================================================================

run-debug: config-certs ## Run in debug mode; x=name for named instance; o=1 forces browser reopen; auth=saml enables SAML (requires AZURE_TENANT=<tenant-guid>) (builds www + cargo)
	@$(MAKE) www
	@cargo build
	@[ -n "$(o)" ] && rm -f "envs/local$(if $(x),-$(x),)/.browser_opened" || true
	@if [ -n "$(x)" ]; then \
		echo "$(BLUE)🔧 Configuring debug instance $(x)...$(NC)"; \
		./scripts/_prepare.sh debug envs/local-$(x); \
		echo "$(GREEN)✅ Debug instance $(x) ready!$(NC)"; \
	else \
		echo "$(BLUE)🔧 Configuring debug environment (dev mode)...$(NC)"; \
		./scripts/_prepare.sh debug envs/local; \
		echo "$(GREEN)✅ Debug dev environment ready!$(NC)"; \
	fi
	@[ "$(auth)" = "saml" ] && ./scripts/_saml-setup.sh "envs/local$(if $(x),-$(x),)" "$(AZURE_TENANT)" || true
	@[ "$(auth)" = "passkey" ] && ./scripts/_passkey-setup.sh "envs/local$(if $(x),-$(x),)" || true
	@if [ -n "$(x)" ]; then \
		RUST_LOG="$(RUST_LOG)" AG_IDENTITY_HASH_PEPPER="$(AG_IDENTITY_HASH_PEPPER)" AG_BACKUP_ENCRYPTION_KEY="$(AG_BACKUP_ENCRYPTION_KEY)" ./scripts/l-run-debug.sh $(x); \
	else \
		RUST_LOG="$(RUST_LOG)" AG_IDENTITY_HASH_PEPPER="$(AG_IDENTITY_HASH_PEPPER)" AG_BACKUP_ENCRYPTION_KEY="$(AG_BACKUP_ENCRYPTION_KEY)" ./scripts/l-run-debug.sh; \
	fi

run-watch: config-certs ## Run with cargo watch (auto-rebuild/restart on Rust changes); x=name for named instance; o=1 forces browser reopen; auth=saml enables SAML (requires AZURE_TENANT=<tenant-guid>)
	@command -v cargo-watch >/dev/null 2>&1 || (echo "$(RED)❌ cargo-watch is not installed. Run: make install-rust-deps$(NC)" && exit 1)
	@$(MAKE) www
	@[ -n "$(o)" ] && rm -f "envs/local$(if $(x),-$(x),)/.browser_opened" || true
	@if [ -n "$(x)" ]; then \
		echo "$(BLUE)🔧 Configuring watch instance $(x)...$(NC)"; \
		./scripts/_prepare.sh debug envs/local-$(x); \
		echo "$(GREEN)✅ Watch instance $(x) ready!$(NC)"; \
	else \
		echo "$(BLUE)🔧 Configuring watch environment (dev mode)...$(NC)"; \
		./scripts/_prepare.sh debug envs/local; \
		echo "$(GREEN)✅ Watch dev environment ready!$(NC)"; \
	fi
	@[ "$(auth)" = "saml" ] && ./scripts/_saml-setup.sh "envs/local$(if $(x),-$(x),)" "$(AZURE_TENANT)" || true
	@[ "$(auth)" = "passkey" ] && ./scripts/_passkey-setup.sh "envs/local$(if $(x),-$(x),)" || true
	@if [ -n "$(x)" ]; then \
		RUST_LOG="$(RUST_LOG)" AG_IDENTITY_HASH_PEPPER="$(AG_IDENTITY_HASH_PEPPER)" AG_BACKUP_ENCRYPTION_KEY="$(AG_BACKUP_ENCRYPTION_KEY)" ./scripts/l-run-watch.sh $(x); \
	else \
		RUST_LOG="$(RUST_LOG)" AG_IDENTITY_HASH_PEPPER="$(AG_IDENTITY_HASH_PEPPER)" AG_BACKUP_ENCRYPTION_KEY="$(AG_BACKUP_ENCRYPTION_KEY)" ./scripts/l-run-watch.sh; \
	fi

run-release: config-release ## Run locally (release mode)
	@RUST_LOG="$(RUST_LOG)" AG_IDENTITY_HASH_PEPPER="$(AG_IDENTITY_HASH_PEPPER)" AG_BACKUP_ENCRYPTION_KEY="$(AG_BACKUP_ENCRYPTION_KEY)" ./scripts/l-run-release.sh

www-dev: www ## Run the frontend app in development mode
	@echo "$(BLUE)🚀 Starting frontend dev server...$(NC)"
	@cd $(WWW_DIR) && npm start

# ==============================================================================
# Docker Commands
# ==============================================================================

.docker-local: Cargo.toml Cargo.lock Dockerfile $(shell find src -name '*.rs' 2>/dev/null)
	@echo "$(BLUE)🐳 Building Docker image locally...$(NC)"
	@./scripts/d-build.sh --name agent-gateway --folder . --version local --dockerfile Dockerfile
	@touch $@
	@echo "$(GREEN)✅ Docker image built!$(NC)"

.docker-local-dev: Cargo.toml Cargo.lock Dockerfile.dev $(shell find src -name '*.rs' 2>/dev/null)
	@echo "$(BLUE)🐳 Building Docker dev image locally...$(NC)"
	@./scripts/d-build.sh --name agent-gateway --folder . --version local-dev --dockerfile Dockerfile.dev
	@touch $@
	@echo "$(GREEN)✅ Docker dev image built!$(NC)"

docker-build-local: .docker-local ## Build Docker image locally (Dockerfile); skips if up-to-date

docker-build-local-dev: .docker-local-dev ## Build Docker dev image locally (Dockerfile.dev); skips if up-to-date

docker-rebuild-local: ## Force rebuild Docker image (Dockerfile)
	@rm -f .docker-local
	@$(MAKE) .docker-local

docker-rebuild-local-dev: ## Force rebuild Docker dev image (Dockerfile.dev)
	@rm -f .docker-local-dev
	@$(MAKE) .docker-local-dev

docker-run: config-docker .docker-local ## Run in Docker (auto-rebuilds if sources changed)
	@./scripts/d-run.sh

docker-run-dev: config-docker .docker-local-dev ## Run in Docker dev mode (debug build, faster; auto-rebuilds if sources changed)
	@TAG=agent-gateway:local-dev ./scripts/d-run.sh

docker-shell: ## Shell into a Docker container for debugging
	@./scripts/d-shell.sh

docker-network: ## Create the Docker network (agent-network)
	@docker network create agent-network 2>/dev/null || echo "Network agent-network already exists."

# Run a cargo test command. The ts-rs export macros write the TypeScript
# bindings straight into www/default/src/generated (tracked) during tests.
# Usage: $(call rust_test,cargo test --bin agent-gateway)
define rust_test
@$(1)
endef

# ==============================================================================
# Testing Commands
# ==============================================================================

test-all: test npm-test ui-test ## Run all tests (Rust + npm + UI)
	@echo "$(GREEN)✅ All tests completed!$(NC)"

test: config-test ## Run all Rust tests (use test=name to filter)
	@echo "$(BLUE)🧪 Running tests...$(NC)"
ifdef test
	$(call rust_test,cargo test --no-fail-fast --all-targets --all-features -- $(test))
else
	$(call rust_test,cargo test --no-fail-fast --all-targets --all-features)
endif
	@echo "$(GREEN)✅ Tests completed!$(NC)"

test-unit: config-test ## Run unit tests only
	@echo "$(BLUE)🧪 Running unit tests...$(NC)"
	$(call rust_test,cargo test --bin agent-gateway)
	@echo "$(GREEN)✅ Unit tests completed!$(NC)"

test-bins: config-test ## Run binary tests only
	@echo "$(BLUE)🧪 Running binary tests...$(NC)"
	$(call rust_test,cargo test --bins)
	@echo "$(GREEN)✅ Binary tests completed!$(NC)"

test-policies: config-test ## Run policy engine tests
	@echo "$(BLUE)🧪 Running policy tests...$(NC)"
	@cargo test --bin agent-gateway policies::opa::tests
	@echo "$(GREEN)✅ Policy tests completed!$(NC)"

test-junit: config-test ## Run tests with nextest and emit JUnit XML (test-results.xml)
	@echo "$(BLUE)🧪 Running tests with JUnit output...$(NC)"
	$(call rust_test,cargo nextest run --no-fail-fast --all-features --profile ci)
	@echo "$(GREEN)✅ JUnit report written to test-results.xml$(NC)"

test-rust-ci: config-test ## Run the CI test flow locally (coverage + surface_bdd)
	@echo "$(BLUE)🧪 Running CI test flow...$(NC)"
	@rm -f coverage.xml $(COVERAGE_PROFILE_ARTIFACTS)
	@set +e; $(LLVM_COV_ENV) cargo llvm-cov nextest --no-clean --no-fail-fast --all-features -P ci --cobertura --output-path coverage.xml --fail-under-lines $(COVERAGE_THRESHOLD) 2>&1 | tee test.log; STATUS=$${PIPESTATUS[0]}; \
	  cp target/llvm-cov-target/nextest/ci/test-results.xml test-results.xml 2>/dev/null || cp target/nextest/ci/test-results.xml test-results.xml 2>/dev/null || true; \
	  if [[ -s coverage.xml ]]; then COV=$$(grep -m1 'line-rate=' coverage.xml | sed 's/.*line-rate="\([0-9.]*\)".*/\1/' | awk '{printf "%.2f%%", $$1*100}'); fi; \
	  echo "$(BLUE)📊 Lines coverage: $${COV:-0.00%}$(NC)"; \
	  cargo test --test surface_bdd 2>&1 | tee surface_bdd_test.log; BDD_STATUS=$$?; \
	  if [[ $$STATUS -ne 0 || $$BDD_STATUS -ne 0 ]]; then echo "$(RED)❌ Test failures: unit/integration=$$STATUS bdd=$$BDD_STATUS$(NC)"; exit 1; fi
	@echo "$(GREEN)✅ CI test flow passed!$(NC)"

test-coverage: config-test ## Run tests with coverage + JUnit report (mirrors CI; outputs coverage.xml + test-results.xml)
	@echo "$(BLUE)🧪 Running tests with coverage...$(NC)"
	@rm -f coverage.xml $(COVERAGE_PROFILE_ARTIFACTS)
	@set +e; $(LLVM_COV_ENV) cargo llvm-cov nextest --no-clean --no-fail-fast --all-features -P ci --cobertura --output-path coverage.xml --fail-under-lines $(COVERAGE_THRESHOLD) 2>&1 | tee test.log; STATUS=$${PIPESTATUS[0]}; \
	  cp target/llvm-cov-target/nextest/ci/test-results.xml test-results.xml 2>/dev/null || cp target/nextest/ci/test-results.xml test-results.xml 2>/dev/null || true; \
	  COV=$$(grep -m1 'line-rate=' coverage.xml | sed 's/.*line-rate="\([0-9.]*\)".*/\1/' | awk '{printf "%.2f%%", $$1*100}'); echo "$(BLUE)📊 Lines coverage: $${COV}$(NC)"; \
	  exit $$STATUS
	@echo "$(GREEN)✅ Coverage completed! JUnit report written to test-results.xml$(NC)"

npm-test: npm-install ## Run frontend unit tests
	@echo "$(BLUE)🧪 Running npm tests...$(NC)"
	@cd $(WWW_DIR) && npm test -- --watchAll=false
	@echo "$(GREEN)✅ npm tests passed!$(NC)"

npm-test-ci: npm-install-ci ## Run frontend unit tests (CI mode)
	@echo "$(BLUE)🧪 Running npm tests (CI mode)...$(NC)"
	@cd $(WWW_DIR) && CI=true npm run test -- --watchAll=false
	@echo "$(GREEN)✅ npm tests (CI mode) passed!$(NC)"

npm-build: npm-install ## Build the frontend app via npm
	@echo "$(BLUE)📦 Running npm build...$(NC)"
	@cd $(WWW_DIR) && npm run build
	@echo "$(GREEN)✅ npm build passed!$(NC)"

npm-build-ci: npm-install-ci ## Build the frontend app via npm (CI mode)
	@echo "$(BLUE)📦 Running npm build (CI mode)...$(NC)"
	@cd $(WWW_DIR) && CI=true npm run build
	@echo "$(GREEN)✅ npm build (CI mode) passed!$(NC)"

ui-test: config-test ## Run UI automation tests (boots gateway in test mode, runs Playwright, tears down)
	@./scripts/l-run-ui-tests.sh
	@echo "$(GREEN)✅ UI tests completed! Run 'make ui-test-report' to view the report.$(NC)"

ui-test-headed: ## Run UI tests with visible browser
	@echo "$(BLUE)🧪 Running UI tests (headed mode)...$(NC)"
	@cd ui-tests && npm install --silent
	@cd ui-tests && npm run test:ui:headed

ui-test-report: ## Open the latest UI test HTML report
	@echo "$(BLUE)📊 Opening UI test report...$(NC)"
	@cd ui-tests && npm run test:ui:report

# ==============================================================================
# Code Quality Commands
# ==============================================================================

clippy: ## Run Clippy linter (autofix)
	@echo "$(BLUE)📎 Running Clippy...$(NC)"
	@cargo clippy --all-targets --all-features --fix --allow-dirty -- -D warnings
	@echo "$(GREEN)✅ Clippy passed!$(NC)"

clippy-ci: ## Run Clippy linter like CI (no autofix, warnings fail)
	@echo "$(BLUE)📎 Running Clippy (CI mode)...$(NC)"
	@cargo clippy --all-targets --all-features -- -D warnings
	@echo "$(GREEN)✅ Clippy CI passed!$(NC)"

fmt: ## Format Rust and frontend code
	@echo "$(BLUE)✨ Formatting code...$(NC)"
	@cargo fmt --all
	@echo "$(BLUE)  📂 Formatting $(WWW_DIR)...$(NC)"
	@(cd $(WWW_DIR) && npm install --silent && npm run format 2>&1 | grep -vF '(unchanged)') || true
	@echo "$(GREEN)✅ Code formatted!$(NC)"

fmt-check: ## Check Rust and frontend formatting (all apps, no changes)
	@echo "$(BLUE)🔍 Checking code format...$(NC)"
	@cargo fmt --all -- --check
	@for dir in $(WWW_DIRS); do \
		echo "$(BLUE)  📂 Checking format in $$dir...$(NC)"; \
		(cd $$dir && npm ci --silent && npm run format:check --if-present) || true; \
	done
	@echo "$(GREEN)✅ Format check passed!$(NC)"

npm-lint: ## Run ESLint on frontend app (autofix)
	@echo "$(BLUE)📎 Running npm lint:fix...$(NC)"
	@echo "$(BLUE)  📂 Linting $(WWW_DIR)...$(NC)"
	@cd $(WWW_DIR) && npm install --silent && npm run lint:fix
	@echo "$(GREEN)✅ npm lint passed!$(NC)"

npm-lint-ci: ## Run ESLint on frontend app like CI (no autofix, fails on errors)
	@echo "$(BLUE)📎 Running npm lint...$(NC)"
	@cd $(WWW_DIR) && npm run lint
	@echo "$(GREEN)✅ CI-equivalent npm lint passed!$(NC)"

shellcheck: ## Lint all Bash scripts with ShellCheck (fails on warnings)
	@echo "$(BLUE)📎 Running ShellCheck...$(NC)"
	@command -v shellcheck >/dev/null 2>&1 || { \
		echo "$(RED)❌ shellcheck not found — install it (brew install shellcheck / apt-get install shellcheck)$(NC)"; \
		exit 1; \
	}
	@shellcheck --severity=warning $$(git ls-files -- '*.sh')
	@echo "$(GREEN)✅ ShellCheck passed!$(NC)"

lint: ## Run all linters (format check + Clippy + ESLint + ShellCheck)
	@$(MAKE) fmt-check
	@$(MAKE) clippy
	@$(MAKE) npm-lint
	@$(MAKE) shellcheck

audit: ## Run security audit (manage ignores in .cargo/audit.toml)
	@echo "$(BLUE)🔍 Running security audit...$(NC)"
	@cargo audit
	@echo "$(BLUE)  Auditing $(WWW_DIR)...$(NC)"
	@(cd $(WWW_DIR) && npm audit --omit=dev 2>/dev/null) || true
	@echo "$(GREEN)✅ Security audit passed!$(NC)"

license-check: ## Check dependency licenses (manage exceptions in deny.toml)
	@echo "$(BLUE)🔍 Checking dependency licenses...$(NC)"
	@cargo deny check licenses
	@echo "$(GREEN)✅ License check passed!$(NC)"

audit-fix: ## Update Rust and frontend deps to patched versions and re-audit
	@echo "$(BLUE)🔍 Updating dependencies and re-auditing...$(NC)"
	@cargo update
	@cargo audit
	@echo "$(BLUE)  Fixing $(WWW_DIR)...$(NC)"
	@(cd $(WWW_DIR) && npm install --silent && npm audit fix --omit=dev 2>/dev/null) || true
	@echo "$(GREEN)✅ Security audit fixed!$(NC)"

check: ## Run cargo check for fast compilation verification
	@echo "$(BLUE)🔍 Running cargo check...$(NC)"
	@cargo check --all-targets --all-features
	@echo "$(GREEN)✅ Check passed!$(NC)"

# --- All-frontend targets: operate on every WWW_DIRS entry ---

fmt-www-all: ## Format Rust and all frontend apps
	@echo "$(BLUE)✨ Formatting code...$(NC)"
	@cargo fmt --all
	@for dir in $(WWW_DIRS); do \
		echo "$(BLUE)  📂 Formatting $$dir...$(NC)"; \
		(cd $$dir && npm install --silent && npm run format 2>&1 | grep -vF '(unchanged)') || true; \
	done
	@echo "$(GREEN)✅ Code formatted!$(NC)"

npm-lint-www-all: ## Run ESLint on all frontend apps (autofix)
	@echo "$(BLUE)📎 Running npm lint:fix...$(NC)"
	@for dir in $(WWW_DIRS); do \
		echo "$(BLUE)  📂 Linting $$dir...$(NC)"; \
		(cd $$dir && npm install --silent && npm run lint:fix --if-present 2>&1 | grep -vF '(unchanged)') || true; \
	done
	@echo "$(GREEN)✅ npm lint passed!$(NC)"

audit-www-all: ## Run Rust and frontend security audit (all apps)
	@echo "$(BLUE)🔍 Running security audit...$(NC)"
	@cargo audit
	@for dir in $(WWW_DIRS); do \
		echo "$(BLUE)  Auditing $$dir...$(NC)"; \
		(cd $$dir && npm ci --silent && npm audit --omit=dev 2>/dev/null) || true; \
	done
	@echo "$(GREEN)✅ Security audit passed!$(NC)"

audit-fix-www-all: ## Update Rust and frontend deps to patched versions (all apps)
	@echo "$(BLUE)🔍 Updating dependencies and re-auditing...$(NC)"
	@cargo update
	@cargo audit
	@for dir in $(WWW_DIRS); do \
		echo "$(BLUE)  Fixing $$dir...$(NC)"; \
		(cd $$dir && npm install --silent && npm audit fix --omit=dev 2>/dev/null) || true; \
	done
	@echo "$(GREEN)✅ Security audit fixed!$(NC)"

browserslist-update: ## Refresh Browserslist data (caniuse-lite) in every frontend app's package-lock.json
	@for dir in $(WWW_DIRS); do \
		echo "$(BLUE)🌐 Updating Browserslist data in $$dir...$(NC)"; \
		(cd $$dir && npx --yes update-browserslist-db@latest) || exit 1; \
	done
	@echo "$(GREEN)✅ Browserslist data updated! Commit the package-lock.json changes.$(NC)"

# ==============================================================================
# Quality Gates
# ==============================================================================

# --- CI targets: check-only, mirrors the CI pipeline ---

node-ci: ## Run CI frontend checks locally (npm ci + lint + build + test)
	@$(MAKE) npm-install-ci
	@$(MAKE) npm-lint-ci
	@$(MAKE) npm-build-ci
	@$(MAKE) npm-test-ci
	@echo "$(GREEN)✅ CI frontend checks passed!$(NC)"

rust-ci: ## Run CI Rust checks locally (fmt, check, clippy, audit, build, test, gw-e2e)
	@$(MAKE) fmt-check
	@$(MAKE) check
	@$(MAKE) clippy-ci
	@$(MAKE) audit
	@$(MAKE) cargo-build-ci
	@$(MAKE) test-rust-ci
	@$(MAKE) gw-e2e
	@echo "$(GREEN)✅ CI Rust checks passed!$(NC)"

ci: ## Run full local preflight mirroring CI
	@$(MAKE) node-ci
	@$(MAKE) rust-ci
	@echo "$(GREEN)✅ Local CI preflight passed!$(NC)"

# --- Local targets: autofix, for development workflow ---

node-local: ## Run frontend checks locally with autofix (fmt + lint --fix + build + test)
	@$(MAKE) npm-install
	@$(MAKE) npm-lint
	@$(MAKE) npm-build
	@$(MAKE) npm-test
	@echo "$(GREEN)✅ Local frontend checks passed!$(NC)"

rust-local: ## Run Rust checks locally with autofix (fmt + clippy --fix + audit + build + test)
	@$(MAKE) fmt
	@$(MAKE) check
	@$(MAKE) clippy
	@$(MAKE) audit
	@$(MAKE) cargo-build
	@$(MAKE) test
	@echo "$(GREEN)✅ Local Rust checks passed!$(NC)"

local: ## Run all local checks with autofix (node-local + rust-local)
	@$(MAKE) node-local
	@$(MAKE) rust-local
	@echo "$(GREEN)✅ All local checks passed!$(NC)"

# Fail if any tracked files were modified by an autofix step.
# Call this after all fmt/fix passes so the error lists all changed files at once.
define check_no_diff
	if ! git --no-pager diff --quiet; then \
		echo "$(RED)❌ Autofix changed files. Stage and commit them, then re-push:$(NC)"; \
		git --no-pager diff --name-only; \
		exit 1; \
	fi
endef

pre-commit-rust: ## Run Rust pre-push checks (fmt + clippy autofix) — fails if any file was changed; tests run in CI
	@echo "$(BLUE)🦀 Running Rust pre-push checks...$(NC)"
	@cargo fmt --all
	@cargo clippy --all-targets --all-features --fix --allow-dirty -- -D warnings
	@$(check_no_diff)
	@echo "$(GREEN)✅ Rust pre-push checks passed!$(NC)"

pre-commit-rust-test: ## Run Rust test suite (pre-push)
	@echo "$(BLUE)🧪 Running Rust tests...$(NC)"
	$(call rust_test,cargo test --no-fail-fast --all-targets --all-features)
	@echo "$(GREEN)✅ Rust tests passed!$(NC)"

pre-commit-node: ## Run Node pre-push checks (fmt + lint autofix) — fails if any file was changed
	@echo "$(BLUE)📦 Running Node pre-push checks...$(NC)"
	@cd $(WWW_DIR) && npm run format --if-present
	@cd $(WWW_DIR) && npm run lint:fix
	@$(check_no_diff)
	@echo "$(GREEN)✅ Node pre-push checks passed!$(NC)"

pre-commit: pre-commit-rust pre-commit-node ## Run all pre-push checks (fmt + autofix) — fails if any file was changed; tests run in CI
	@$(check_no_diff)
	@echo "$(GREEN)✅ Pre-commit checks passed!$(NC)"

# ==============================================================================
# Quick Workflows
# ==============================================================================

dev: www cargo-build ## Build backend and frontend for development
	@echo "$(GREEN)✅ Development build ready!$(NC)"

full-setup: install-deps dev ## Complete project setup from scratch
	@echo "$(GREEN)✅ Full setup completed! Run 'make run' to start the gateway.$(NC)"

release: www cargo-release ## Build backend and frontend for release
	@echo "$(GREEN)✅ Release build ready!$(NC)"

# ==============================================================================
# Certificate & Security Commands
# ==============================================================================

generate-cert: ## Generate self-signed TLS certificates
	@echo "$(BLUE)🔐 Generating TLS certificates...$(NC)"
	@./scripts/certs/generate-cert.sh
	@echo "$(GREEN)✅ Certificates generated!$(NC)"

trust-cert: ## Add self-signed cert to system trust store
	@echo "$(BLUE)🔐 Adding certificate to system trust store...$(NC)"
	@./scripts/certs/trust-cert.sh $(CERT_PATH)
	@echo "$(GREEN)✅ Certificate trusted!$(NC)"

derive-x402-addresses: ## Derive Ethereum addresses from x402.json facilitator keys
	@echo "$(BLUE)🔐 Deriving x402 facilitator addresses...$(NC)"
	@./scripts/x402/derive-facilitator-addresses.sh $(or $(X402_CONFIG),envs/local/config/x402.json) $(if $(UPDATE),--update)
	@echo "$(GREEN)✅ x402 addresses derived!$(NC)"

# ==============================================================================
# Mediator Commands
# ==============================================================================

mediator: mediator-up
mediator-start: mediator-up

mediator-up: ## Set up DIDComm mediator server
	@echo "$(BLUE)📡 Setting up DIDComm mediator...$(NC)"
	@./scripts/mediator/mediator-start.sh
	@echo "$(GREEN)✅ Mediator configured!$(NC)"

mediator-stop: mediator-down

mediator-down: ## Tear down DIDComm mediator server
	@echo "$(BLUE)📡 Tearing down DIDComm mediator...$(NC)"
	@./scripts/mediator/mediator-stop.sh
	@echo "$(GREEN)✅ Mediator stopped!$(NC)"

# ==============================================================================
# Gateway E2E (g2g_bdd against real DIDComm mediators)
# ==============================================================================
G2G_MEDIATOR_PORT ?= 7037

gw-e2e: clean-e2e ## Run the gateway-to-gateway BDD E2E suite (federation)
	@echo "$(BLUE)🧪 Running g2g_bdd...$(NC)"
	@parallelism="$${G2G_BDD_PARALLELISM:-8}"; \
	if [ "$$parallelism" = "1" ]; then \
		G2G_BDD_PARALLELISM="$$parallelism" \
		FABRIC_BDD_MANAGED_MEDIATOR="1" \
		FABRIC_BDD_MEDIATOR_PORT="$(G2G_MEDIATOR_PORT)" \
		FABRIC_BDD_DID_METHOD="peer" \
		RUST_LOG="$(if $(RUST_LOG),$(RUST_LOG),info)" \
			cargo test --test g2g_bdd $(CARGO_TEST_ARGS); \
	else \
		G2G_BDD_PARALLELISM="$$parallelism" \
		FABRIC_BDD_MANAGED_MEDIATOR="1" \
		FABRIC_BDD_DID_METHOD="peer" \
		RUST_LOG="$(if $(RUST_LOG),$(RUST_LOG),info)" \
			cargo test --test g2g_bdd $(CARGO_TEST_ARGS); \
	fi

# Prune any leftover BDD mediator containers + networks + temp dirs from a
# prior run that panicked before its Drop could tear the mediator down. Runs
# as a `gw-e2e` pre-step so a normal `make gw-e2e` is self-healing.
clean-e2e: ## Remove leftover g2g_bdd mediator containers + networks + temp dirs
	@echo "$(BLUE)🧹 Cleaning up leftover BDD containers...$(NC)"
	@docker ps -aq --filter "name=g2g-bdd-mediator" 2>/dev/null \
		| xargs -r docker rm -f >/dev/null 2>&1 || true
	@docker network ls -q --filter "name=g2g-bdd-mediator" 2>/dev/null \
		| xargs -r docker network rm >/dev/null 2>&1 || true
	@rm -rf tmp/g2g-* 2>/dev/null || true
	@echo "$(GREEN)✅ BDD test containers cleaned!$(NC)"

# Needs Node >= 20.18.1, git and openssl; the first run fetches the pinned suite
# and reference server. ARGS passes options through, e.g. ARGS="--unit-tests" or
# ARGS="--only access-point,legacy". See scripts/mcp-conformance/README.md.
mcp-conformance: ## Run the MCP 2026-07-28 conformance harness (ARGS="--unit-tests" etc.)
	@./scripts/mcp-conformance/run.sh $(ARGS)

mcp-conformance-legacy: ## Run only the MCP legacy (2024-11-05) compatibility checks
	@./scripts/mcp-conformance/run.sh --only legacy $(ARGS)

# ==============================================================================
# Storage Commands
# ==============================================================================

clean-info: ## Clear local environment storage
	@echo "$(YELLOW)⚠️ 🧹 This will delete $(INFO). Press Ctrl+C to cancel.$(NC)"
	@sleep 2

clean-local-storage: INFO="local storage"
clean-local-storage: clean-info ## Clear local storage
	@rm -rf envs/local/_storage/* 2>/dev/null || true
	@echo "$(GREEN)✅ Local storage cleared!$(NC)"

clean-envs-local: INFO="environment local files"
clean-envs-local: clean-info ## Clean environment local files
	@rm -rf envs/local 2>/dev/null || true
	@echo "$(GREEN)✅ Environment local files cleaned!$(NC)"

clean-envs: INFO="environment files"
clean-envs: clean-info ## Clean environment files
	@rm -rf envs 2>/dev/null || true
	@echo "$(GREEN)✅ Environment files cleaned!$(NC)"

clean-cargo: INFO="cargo build artifacts"
clean-cargo: clean-info ## Clean cargo build artifacts
	@cargo clean 2>/dev/null || true
	@echo "$(GREEN)✅ Cargo build artifacts cleaned!$(NC)"

clean-www: INFO="www artifacts"
clean-www: clean-info ## Clean www artifacts
	@rm -rf $(WWW_DIR)/build 2>/dev/null || true
	@rm -rf $(WWW_DIR)/node_modules 2>/dev/null || true
	@echo "$(GREEN)✅ WWW artifacts cleaned!$(NC)"

clean-artifacts: INFO="artifacts"
clean-artifacts: clean-info clean-cargo clean-www ## Clean all build artifacts (cargo + www)
	@echo "$(GREEN)✅ Artifacts cleaned!$(NC)"

clean-all: INFO="all local files"
clean-all: clean-info clean-artifacts clean-envs ## Clean everything including node_modules
	@echo "$(GREEN)✅ Full clean completed!$(NC)"

# ==============================================================================
# Documentation Commands
# ==============================================================================

docs-list: ## List documentation files
	@echo "$(BLUE)📚 Documentation is in docs/ (Markdown files):$(NC)"
	@find docs -type f -name '*.md' | sort | sed 's|docs/||'

# ==============================================================================
# Utility Commands
# ==============================================================================

ngrok: ## Start ngrok tunnel (default port 8440)
	@echo "$(BLUE)🔗 Starting ngrok tunnel on port $(or $(PORT),8440)...$(NC)"
	@ngrok http $(or $(PORT),8440)

demo-multi-tenancy: ## Run the management multi-tenancy demo against a local gateway
	@./scripts/demo-multi-tenancy.sh $(ARGS)

# ==============================================================================
# A2A Integration Testing Commands
# ==============================================================================

itest-a2a: www ## Run A2A integration tests (requires monorepo context)
	@echo "$(RED)❌ A2A integration tests require the full monorepo. Run from the monorepo root.$(NC)"
	@exit 1

itest-a2a-setup: ## Set up A2A integration test environment (requires monorepo context)
	@echo "$(RED)❌ A2A integration tests require the full monorepo. Run from the monorepo root.$(NC)"
	@exit 1

itest-a2a-run: ## Run A2A tests only (requires monorepo context)
	@echo "$(RED)❌ A2A integration tests require the full monorepo. Run from the monorepo root.$(NC)"
	@exit 1

itest-a2a-teardown: ## Tear down A2A test environment (requires monorepo context)
	@echo "$(RED)❌ A2A integration tests require the full monorepo. Run from the monorepo root.$(NC)"
	@exit 1

itest-a2a-clean: ## Clean A2A test artifacts
	@echo "$(BLUE)🧹 Cleaning A2A test artifacts...$(NC)"
	@echo "$(GREEN)✅ A2A test artifacts cleaned!$(NC)"

itest-a2a-shopping: ## Run Shopping Agent (requires monorepo context)
	@echo "$(RED)❌ A2A integration tests require the full monorepo. Run from the monorepo root.$(NC)"
	@exit 1
