// When you want to introduce a new node type, add it to this
// union and then add a corresponding NodeDefinition in
// elements/registry.ts

export type SurfaceNodeType =
  | 'surface'
  | 'access-point'
  | 'target'
  | 'transit-point-a2a'
  | 'transit-point-mcp'
  | 'transit-point-ap2'
  | 'policy'
  | 'payment'
  | 'identity'
  | 'networking'
  | 'rate-limit'
  | 'trust-recorder'
  | 'trust-check'
  | 'custom-metadata'
  | 'metadata-extraction'
  | 'extension-validation'
  | 'extension-rules'
  | 'target-variant'
  | 'transit-config'
  | 'caller-auth'
  | 'credential-delegation'
  | 'workload-binding'
  | 'mcp-tool-gating'
  | 'npc-actor'
  | 'npc-agent'
  | 'npc-endpoint'
  | 'npc-server'
  | 'npc-database'
  | 'npc-service'
  | 'human'
  | 'caller'
  | 'local-gateway-hop'
  | 'remote-gateway'
  | 'remote-channel';
