#!/bin/bash

# -x Print out all executed commands to the terminal.
# set -x

# -e  Exit immediately if a command exits with a non-zero status.
set -e

source "$(dirname "$0")/_env.sh"
source "$(dirname "$0")/_portable.sh"

# Values the sourced helpers above must provide.
: "${envs_dir:?_env.sh must set envs_dir}"

# Strip --auto-accept from args before positional parsing.
auto_accept=false
_filtered_args=()
for _arg in "$@"; do
  if [[ "${_arg}" == "--auto-accept" ]]; then
    auto_accept=true
  else
    _filtered_args+=("${_arg}")
  fi
done
set -- "${_filtered_args[@]}"

# An interactive prompt needs a terminal on both ends: stdin to read the answer
# and stdout to show the question. If either is redirected (CI, a test harness,
# `make www-rebuild >/dev/null`), the prompt is unanswerable, so auto-accept
# instead of blocking on `read` forever.
if [[ ! -t 0 || ! -t 1 ]]; then
  auto_accept=true
fi

target="$1"
target_dir="$2"

current_dir=$(pwd)
target_dir="${current_dir}/${target_dir}"

# ----------------------------------------------------------------------------
# Port assignment
# ----------------------------------------------------------------------------
# For local-* instances we derive a deterministic port offset from the suffix:
#   - numeric suffix N   → offset = N   (local-1 → 1, local-2 → 2, ...)
#   - non-numeric suffix → offset = 100 + (cksum(suffix) % 900)
#                          (keeps named instances out of the numeric range; 900 slots → low collision chance)
#   - no suffix (envs/local) → offset = 0
# Computed ports are persisted to ${target_dir}/instance.env (kept outside
# config/, which is owned by the service) so run scripts source them
# instead of guessing or scanning.
assign_ports() {
  local dir="$1"
  local base_name
  base_name=$(basename "${dir}")
  local suffix=""
  local offset=0

  if [[ "${base_name}" == local-* ]]; then
    suffix="${base_name#local-}"
  fi

  if [[ -z "${suffix}" ]]; then
    offset=0
  elif [[ "${suffix}" =~ ^[0-9]+$ ]]; then
    offset=$(( suffix ))
  else
    local hash
    hash=$(printf '%s' "${suffix}" | cksum | awk '{print $1}')
    offset=$(( 100 + (hash % 900) ))
  fi

  http_port=$(( DEFAULT_HTTP_PORT + offset ))
  https_port=$(( DEFAULT_HTTPS_PORT + offset ))
  outbound_port=$(( DEFAULT_OUTBOUND_PORT + offset ))
  frontend_port=$(( DEFAULT_FRONTEND_PORT + offset ))

  # Collision check: scan all sibling local-*/instance.env files.
  local f other_http other_https other_outbound other_frontend
  for f in "${envs_dir}"/local-*/instance.env "${envs_dir}"/local/instance.env; do
    [[ -f "${f}" ]] || continue
    [[ "${f}" == "${dir}/instance.env" ]] && continue
    [[ "${f}" == *".bak/"* ]] && continue
    other_http=$(grep -E '^HTTP_PORT='     "${f}" | cut -d= -f2)
    other_https=$(grep -E '^HTTPS_PORT='   "${f}" | cut -d= -f2)
    other_outbound=$(grep -E '^OUTBOUND_PORT=' "${f}" | cut -d= -f2)
    other_frontend=$(grep -E '^FRONTEND_PORT=' "${f}" | cut -d= -f2)
    if [[ "${other_http}" == "${http_port}" \
       || "${other_https}" == "${https_port}" \
       || "${other_outbound}" == "${outbound_port}" \
       || "${other_frontend}" == "${frontend_port}" ]]; then
      echo "❌ Port collision with ${f}:"
      echo "   wanted   HTTP=${http_port} HTTPS=${https_port} OUTBOUND=${outbound_port} FRONTEND=${frontend_port}"
      echo "   existing HTTP=${other_http} HTTPS=${other_https} OUTBOUND=${other_outbound} FRONTEND=${other_frontend}"
      echo "   Pick a different suffix (x=...) or remove the conflicting env."
      exit 1
    fi
  done

  mkdir -p "${dir}"
  cat > "${dir}/instance.env" <<EOF
# Generated by scripts/_prepare.sh — do not edit by hand.
HTTP_PORT=${http_port}
HTTPS_PORT=${https_port}
OUTBOUND_PORT=${outbound_port}
FRONTEND_PORT=${frontend_port}
EOF
  echo "🔢 Ports for $(basename "${dir}"): HTTP=${http_port} HTTPS=${https_port} OUTBOUND=${outbound_port} FRONTEND=${frontend_port}"
}

# Prints the connection details a tunnel/proxy needs to expose <public_url>.
# Usage: show_proxy_info <public_url> <local_port>
show_proxy_info() {
  local url="$1" port="$2"

  local ws_label="🔌 Server (WebSocket):"
  local pt_label="🔢 Proxy port:"
  local gw_label="🌐 Gateway public URL:"
  local _lmax=${#ws_label}
  (( ${#pt_label} > _lmax )) && _lmax=${#pt_label}
  (( ${#gw_label} > _lmax )) && _lmax=${#gw_label}

  echo ""
  printf '\033[0;32m📋 Tunnel connection details - use these when configuring a tunnel or proxy:\033[0m\n'
  printf "   %-${_lmax}s  %s\n" "${ws_label}" "ws://localhost:${port}"
  printf "   %-${_lmax}s  \033[1;33m%s\033[0m\n" "${pt_label}" "${port}"
  printf "   %-${_lmax}s  %s\n" "${gw_label}" "${url}"
  echo ""
}

# Default ports for non-local targets (docker, etc.)
http_port=${3:-8080}
https_port=${4:-8443}
outbound_port=${DEFAULT_OUTBOUND_PORT}
frontend_port=${DEFAULT_FRONTEND_PORT}

if [[ "${target_dir}" == *"/local"* ]]; then
  assign_ports "${target_dir}"
fi

echo "📦 Preparing ${target} env ${target_dir}..."

(mkdir -p "${target_dir}" && echo "✅ ${target_dir} directory created") || echo "✅ ${target_dir} directory exist"

if [[ ! -f "${target_dir}/certs/cert.pem" ]]
then
  pushd "${target_dir}"
  cp -r "${current_dir}/envs/certs" .
  popd
fi

regenerate_config_toml=false
config_toml="${target_dir}/config/config.toml"
previous_auth_mode=""

if [[ ! -f "${config_toml}" ]]
then
  regenerate_config_toml=true
else
  missing_field=""
  if ! grep -qE '^limits[[:space:]]*=' "${config_toml}"
  then
    missing_field="config_files.limits"
  elif ! grep -qE '^backup_encryption_key[[:space:]]*=' "${config_toml}"
  then
    missing_field="backup_encryption_key"
  fi

  if [[ -n "${missing_field}" ]]
  then
    echo "⚠️  Existing config.toml is missing ${missing_field}. Backing it up to config.toml.bak and regenerating it."
    if [[ "${auto_accept}" != "true" ]]; then
      printf "⏎  Press Enter to continue... "
      read _pause
    fi
    previous_auth_mode=$(grep -E '^auth_mode[[:space:]]*=' "${config_toml}" | sed -E 's/^auth_mode[[:space:]]*=[[:space:]]*"([^"]+)"/\1/' || true)
    cp "${config_toml}" "${config_toml}.bak"
    regenerate_config_toml=true
  fi
fi

if [[ "${regenerate_config_toml}" == "true" ]]
then
  mkdir -p "${target_dir}/config"

  echo "🦀 Building debug binary for bootstrap generation..."
  cargo build

  if [[ "${target_dir}" == *"/local"* ]]
  then
    # ${agent_name}
    ./target/debug/agent-gateway \
      --generate-bootstrap \
      --base-folder "${target_dir}" \
      --cors-origins "http://localhost:${http_port},http://127.0.0.1:${http_port},http://0.0.0.0:${http_port},http://localhost:${frontend_port}" > "${target_dir}/config/config.toml"
  fi

  if [[ "${target_dir}" == *"/docker"* ]]
  then
    # ${agent_name}
    ./target/debug/agent-gateway \
      --generate-bootstrap \
      --base-folder "/app" \
      --cors-origins "http://localhost:8080,http://127.0.0.1:8080,http://0.0.0.0:8080" > "${target_dir}/config/config.toml"
  fi

  if [[ -n "${previous_auth_mode}" ]]
  then
    sedi "s/^auth_mode = \".*\"/auth_mode = \"${previous_auth_mode}\"/" "${config_toml}"
    echo "✅ auth_mode re-applied: ${previous_auth_mode}"
  fi
fi

if [[ ! -f "${target_dir}/config/gateway.json" ]]
then
  # Determine which template to use (all local* instances share the local template)
  if [[ "${target_dir}" == *"/local"* ]]
  then
    gateway_template="local"
  elif [[ "${target_dir}" == *"/docker"* ]]
  then
    gateway_template="docker"
  else
    gateway_template="${target_dir}"
  fi

  gateway_url=""          # full URL as entered, e.g. https://example.com:8443
  gateway_domain=""       # hostname only — no scheme, no port (used for rp_id)
  gateway_outbound_url="" # full URL for outbound listener (https://host:port)
  if [[ "${target_dir}" == *"/local"* ]]
  then
    if [[ "${auto_accept}" == "true" ]]; then
      gateway_url=""
    else
      printf "🌐 Enter public URL for this gateway (e.g. https://inbound-fabric-1.example.com, leave empty for localhost): "
      read gateway_url
    fi
    if [[ "${auto_accept}" == "true" ]]; then
      gateway_outbound_url=""
    else
      printf "🌐 Enter public URL for outbound gateway (e.g. https://outbound-fabric-1.example.com, leave empty for none): "
      read gateway_outbound_url
    fi

    if [[ -n "${gateway_url}" ]]
    then
      # Strip scheme (https:// or http://) then strip any path, then strip :port
      gateway_domain="${gateway_url#*://}"
      gateway_domain="${gateway_domain%%/*}"
      gateway_domain="${gateway_domain%%:*}"
    fi

    if [[ -n "${gateway_url}" ]]; then
      show_proxy_info "${gateway_url}" "${http_port}"
    else
      echo "✅ Gateway public URL: localhost (no public domain set)"
    fi

    if [[ -n "${gateway_outbound_url}" ]]; then
      show_proxy_info "${gateway_outbound_url}" "${outbound_port}"
    else
      echo "✅ Outbound gateway public URL: none (no outbound listener configured)"
    fi

    if [[ ( -n "${gateway_url}" || -n "${gateway_outbound_url}" ) && "${auto_accept}" != "true" ]]; then
      printf "⏎  Press Enter to continue... "
      read _pause
    fi

    if [[ ! -n "${gateway_url}" ]]
    then
      echo "No public gateway URL entered — using localhost for WebAuthn and CORS."
      gateway_url="http://localhost:${http_port}"
      gateway_domain="localhost"
    fi
  fi

  cp config/examples/gateway.example.json "${target_dir}/config/gateway.json"

  if [[ "${gateway_template}" == "local" ]]; then
    # Replace "path": "www", with "path": "../../www/build",
    # so the local dev dashboard is served instead of the default build.
    sedi 's|"path": "www"|"path": "../../www/build"|' "${target_dir}/config/gateway.json"
    sedi 's|"path": "_storage/avatars"|"path": "../_storage/avatars"|' "${target_dir}/config/gateway.json"
    # Replace default ports with the instance-specific ports
    sedi "s/\"port\": 8080/\"port\": ${http_port}/g" "${target_dir}/config/gateway.json"
    sedi "s/\"port\": 8443/\"port\": ${https_port}/g" "${target_dir}/config/gateway.json"
    sedi "s/\"port\": 9000/\"port\": ${outbound_port}/g" "${target_dir}/config/gateway.json"
    sedi "s|http://localhost:8080|http://localhost:${http_port}|g" "${target_dir}/config/gateway.json"
    sedi "s|https://localhost:8443|https://localhost:${https_port}|g" "${target_dir}/config/gateway.json"
    sedi "s|http://localhost:9000|http://localhost:${outbound_port}|g" "${target_dir}/config/gateway.json"

    if [[ -n "${gateway_url}" ]]; then
      # did.domain — host:port, no scheme
      sedi "s|\"domain\": \"YOUR_DOMAIN\"|\"domain\": \"${gateway_domain}\"|g" "${target_dir}/config/gateway.json"
      # webauthn.rp_id — hostname only, no scheme, no port
      sedi "s|\"rp_id\": \"YOUR_DOMAIN\"|\"rp_id\": \"${gateway_domain}\"|g" "${target_dir}/config/gateway.json"
      # webauthn.external_origin — full URL with port (same as did.domain)
      sedi "s|\"external_origin\": \"https://YOUR_DOMAIN\"|\"external_origin\": \"${gateway_url}\"|g" "${target_dir}/config/gateway.json"
      # listener external_urls — replace the template placeholder full URL (HTTP listener)
      sedi "s|https://YOUR_DOMAIN|${gateway_url}|g" "${target_dir}/config/gateway.json"
      # Also inject the proxy URL into the HTTPS listener so /.well-known/did.json
      # resolves correctly when served through the proxy tunnel (HTTPS port).
      sedi "s|\"https://localhost:${https_port}\"|\"${gateway_url}\", \"https://localhost:${https_port}\"|g" "${target_dir}/config/gateway.json"
    else
      # WebAuthn external_origin must match the frontend dev server origin
      # (frontend_port was set above by assign_ports for /local targets)
      sedi "s|\"external_origin\": \"https://YOUR_DOMAIN\"|\"external_origin\": \"http://localhost:${frontend_port}\"|g" "${target_dir}/config/gateway.json"
    fi
    if [[ -n "${gateway_outbound_url}" ]]; then
      sedi "s|https://YOUR_OUTBOUND_DOMAIN|${gateway_outbound_url}|g" "${target_dir}/config/gateway.json"
    else
      # If no outbound URL was provided but gateway_url was, then set it to gateway_url
      if [[ -n "${gateway_url}" ]]; then
        sedi "s|https://YOUR_OUTBOUND_DOMAIN|${gateway_url}|g" "${target_dir}/config/gateway.json"
      else
        # If no outbound URL was provided, remove the entry from the outbound listener's external_urls array
        sedi "s|\"https://YOUR_OUTBOUND_DOMAIN\",||g" "${target_dir}/config/gateway.json"
      fi
    fi
  fi

  if [[ "${gateway_template}" == "docker" ]]
  then
    # Docker local evaluation: resolve the WebAuthn / DID placeholders to
    # localhost so `docker compose up` and `make docker-run` start without
    # hand-editing gateway.json. Without this the gateway crash-loops on
    # "rp_id is not an effective_domain of rp_origin". The external_origin must
    # match the URL the browser opens for passkey login to work; docker-compose.yml
    # serves the dashboard over TLS at https://localhost:8443, so pin it there.
    # For a real deployment, override webauthn.rp_id, webauthn.external_origin,
    # and the did.domain with your public host.
    docker_domain="localhost"
    docker_url="https://localhost:8443"
    sedi "s|\"domain\": \"YOUR_DOMAIN\"|\"domain\": \"${docker_domain}\"|g" "${target_dir}/config/gateway.json"
    sedi "s|\"rp_id\": \"YOUR_DOMAIN\"|\"rp_id\": \"${docker_domain}\"|g" "${target_dir}/config/gateway.json"
    sedi "s|\"external_origin\": \"https://YOUR_DOMAIN\"|\"external_origin\": \"${docker_url}\"|g" "${target_dir}/config/gateway.json"
    sedi "s|https://YOUR_DOMAIN|${docker_url}|g" "${target_dir}/config/gateway.json"
    sedi "s|\"https://YOUR_OUTBOUND_DOMAIN\",||g" "${target_dir}/config/gateway.json"
  fi
fi

# Always (re)apply the dashboard static path for local envs so a stale path
# from a previous run can never be served. Idempotent: matches both the
# template placeholder ("www") and any previously-rewritten absolute path
# pointing at www, www/build, or www/default/build.
if [[ "${target_dir}" == *"/local"* && -f "${target_dir}/config/gateway.json" ]]
then
  expected_path="${current_dir}/${WWW_DIR:-www/default}/build"
  gateway_json="${target_dir}/config/gateway.json"

  if ! command -v jq >/dev/null 2>&1; then
    echo "❌ jq is required to update dashboard static path. Install with: brew install jq"
    exit 1
  fi

  updated=$(jq --arg expected "${expected_path}" \
               --arg http_origin "http://localhost:${http_port}" \
               --arg frontend_origin "http://localhost:${frontend_port}" '
    walk(
      if type == "object"
         and .type == "static"
         and (.path | type == "string")
         and (.path == "www" or (.path | test("/www(/build|/default/build)?$")))
      then .path = $expected
      else .
      end
    )
    | .cors = ([$http_origin, $frontend_origin] + (.cors // []) | unique)
  ' "${gateway_json}")

  if [[ "${updated}" != "$(cat "${gateway_json}")" ]]; then
    printf '%s\n' "${updated}" > "${gateway_json}"
    echo "✅ dashboard static path → ${expected_path}"
  else
    echo "✅ dashboard static path already at ${expected_path}"
  fi
fi

# gateway.json is copied from the example only once, so later-shipped
# integration categories and types (e.g. `audit`) never reach an existing env.
# Add the ones it lacks, matched by enum_value; entries already present keep
# their local edits.
if [[ -f "${target_dir}/config/gateway.json" ]]
then
  gateway_json="${target_dir}/config/gateway.json"

  if ! command -v jq >/dev/null 2>&1; then
    echo "❌ jq is required to sync integration categories and types. Install with: brew install jq"
    exit 1
  fi

  # The `channel` category was renamed to `surface`: replace the legacy entry
  # with the shipped one instead of adding a second Surface category.
  if jq -e 'any(.integration.categories[]?; .enum_value == "channel")' "${gateway_json}" >/dev/null; then
    updated=$(jq --slurpfile example ./config/examples/gateway.example.json '
      ($example[0].integration.categories[] | select(.enum_value == "surface")) as $surface
      | .integration.categories |= map(if .enum_value == "channel" then $surface else . end)
    ' "${gateway_json}")
    printf '%s\n' "${updated}" > "${gateway_json}"
    echo "✅ gateway.json integration category channel renamed to surface"
  fi

  added=$(jq -r --slurpfile example ./config/examples/gateway.example.json '
    . as $env
    | ["categories", "types"][] as $key
    | ($env.integration[$key] // []) as $have
    | ($example[0].integration[$key] // [])[]
    | select(.enum_value as $v | any($have[]; .enum_value == $v) | not)
    | "\($key):\(.enum_value)"
  ' "${gateway_json}")

  if [[ -n "${added}" ]]; then
    updated=$(jq --slurpfile example ./config/examples/gateway.example.json '
      def add_missing($key):
        ($example[0].integration[$key] // []) as $shipped
        | (.integration[$key] // []) as $have
        | .integration[$key] = $have + [
            $shipped[] | select(.enum_value as $v | any($have[]; .enum_value == $v) | not)
          ];
      .integration //= {}
      | add_missing("categories")
      | add_missing("types")
    ' "${gateway_json}")
    printf '%s\n' "${updated}" > "${gateway_json}"
    echo "✅ gateway.json integration entries added from example: $(echo "${added}" | paste -sd ' ' -)"
  else
    echo "✅ gateway.json integration categories and types already include the example's"
  fi
fi

if [[ ! -f "${target_dir}/config/metrics.json" ]]
then
  cp ./config/examples/metrics.example.json "${target_dir}/config/metrics.json"
fi

if [[ ! -f "${target_dir}/config/limits.json" ]]
then
  cp ./config/examples/limits.example.json "${target_dir}/config/limits.json"
fi

if [[ ! -f "${target_dir}/config/x402-proxy.json" ]]
then
  cp ./config/examples/x402-proxy.example.json "${target_dir}/config/x402-proxy.json"
fi

if [[ ! -f "${target_dir}/config/rbac.json" ]]
then
  cp ./config/examples/rbac.example.json "${target_dir}/config/rbac.json"
fi

if [[ ! -f "${target_dir}/config/saml.json" ]]
then
  cp ./config/examples/saml.example.json "${target_dir}/config/saml.json"
fi

if [[ ! -f "${target_dir}/config/x402.json" ]]
then
  cp ./config/examples/x402.example.json "${target_dir}/config/x402.json"
fi

mkdir -p "${target_dir}/config/agent_surface_templates"
# Sync only files that are not already present so newly-shipped example
# templates propagate on every prepare, while env-local additions/edits are
# preserved. Copy per entry instead of `cp -n`: BSD/macOS `cp -n` exits 1 when
# it skips an existing file, which would abort this `set -e` script on reruns.
for _tmpl in ./config/examples/agent_surface_templates/*; do
  [[ -e "${_tmpl}" ]] || continue
  _dest="${target_dir}/config/agent_surface_templates/$(basename "${_tmpl}")"
  [[ -e "${_dest}" ]] || cp -R "${_tmpl}" "${_dest}"
done

# Persist URL_LOCAL (always localhost) and URL_PROXY (gateway_url when
# provided) to instance.env so 'make testkit-* x=<name> h=l|h=p' can resolve
# the correct URL without guessing.
if [[ "${target_dir}" == *"/local"* ]]; then
  _testkit_local="http://localhost:${http_port}"
  if grep -q '^URL_LOCAL=' "${target_dir}/instance.env" 2>/dev/null; then
    sedi "s|^URL_LOCAL=.*|URL_LOCAL=${_testkit_local}|" "${target_dir}/instance.env"
  else
    echo "URL_LOCAL=${_testkit_local}" >> "${target_dir}/instance.env"
  fi
  echo "🧪 URL_LOCAL → ${_testkit_local}"

  if [[ -n "${gateway_url}" ]]; then
    if grep -q '^URL_PROXY=' "${target_dir}/instance.env" 2>/dev/null; then
      sedi "s|^URL_PROXY=.*|URL_PROXY=${gateway_url}|" "${target_dir}/instance.env"
    else
      echo "URL_PROXY=${gateway_url}" >> "${target_dir}/instance.env"
    fi
    echo "🧪 URL_PROXY → ${gateway_url}"
  else
    # Derive proxy URL from .did.domain in gateway.json when no gateway_url was given.
    _proxy_url=""
    if [[ -f "${target_dir}/config/gateway.json" ]]; then
      _domain=$(jq -r '.did.domain // empty' "${target_dir}/config/gateway.json" 2>/dev/null)
      [[ -n "${_domain}" ]] && _proxy_url="https://${_domain}"
    fi
    if grep -q '^URL_PROXY=' "${target_dir}/instance.env" 2>/dev/null; then
      sedi "s|^URL_PROXY=.*|URL_PROXY=${_proxy_url}|" "${target_dir}/instance.env"
    else
      echo "URL_PROXY=${_proxy_url}" >> "${target_dir}/instance.env"
    fi
    [[ -n "${_proxy_url}" ]] && echo "🧪 URL_PROXY → ${_proxy_url}"
  fi
fi

echo "✅ ${target} env ${target_dir} preparation completed!"
