# shellcheck shell=bash
# Sourced helpers shared by l-run-debug.sh and l-run-watch.sh.
# Requires: repo_dir, target_dir, www_dir, ui_port set before each call.
#
# This file is a library: `local_env_dir`/`repo_dir`/`www_dir` are provided by
# the sourcing script (via _env.sh), and `http_port`/`NPM_PID` are set here for
# the caller to consume. ShellCheck cannot see either side of that contract from
# this file alone, so SC2154 and SC2034 are disabled for the file rather than
# per line.
# shellcheck disable=SC2154,SC2034

resolve_target_dir() {
  local x="${1:-}"
  if [[ -n "${x}" ]]; then
    target_dir="${local_env_dir}-${x}"
  else
    target_dir="${local_env_dir}"
  fi
  if [[ ! -d "${target_dir}" ]]; then
    echo "❌ ${target_dir} directory does not exist, pls run 'make help' for guidance on setting up environments"
    exit 1
  fi
}

source_ports() {
  local ports_env="${target_dir}/instance.env"
  if [[ ! -f "${ports_env}" ]]; then
    echo "❌ ${ports_env} not found — run 'make config-debug' first"
    exit 1
  fi
  # instance.env is generated by _prepare.sh at runtime, so its path is not a
  # constant ShellCheck can follow.
  # shellcheck disable=SC1090
  source "${ports_env}"
  https_port="${HTTPS_PORT}"
  http_port="${HTTP_PORT}"
  ui_port="${FRONTEND_PORT}"
  export PORT="${ui_port}"
  # Use 127.0.0.1 instead of `localhost` — the Rust gateway binds IPv4 only
  # (0.0.0.0), and Node 17+ resolves `localhost` to ::1 first, which fails
  # with ECONNREFUSED before falling back to IPv4.
  export VITE_BACKEND_URL="https://127.0.0.1:${https_port}"
  export REACT_APP_BACKEND_URL="https://127.0.0.1:${https_port}"
  unset REACT_APP_WS_URL
}

# start_frontend <ready_pid>
# Installs deps, kills stale port, opens browser once, starts npm dev server.
# Sets NPM_PID in the caller's scope.
start_frontend() {
  local ready_pid="${1}"
  cd "${repo_dir}/${www_dir}" || return 1
  npm install --silent
  lsof -ti :"${ui_port}" | xargs kill -9 2>/dev/null || true
  local open_url
  open_url=$(jq -r '.. | objects | select(has("external_origin")) | .external_origin' "${target_dir}/config/gateway.json" 2>/dev/null | head -1)
  open_url="${open_url:-http://localhost:${ui_port}}"
  local browser_marker="${target_dir}/.browser_opened"
  if [[ ! -f "${browser_marker}" ]]; then
    if command -v open >/dev/null 2>&1; then
      (sleep 4 && kill -0 "${ready_pid}" 2>/dev/null && open "${open_url}" && touch "${browser_marker}") &
    elif command -v xdg-open >/dev/null 2>&1; then
      (sleep 4 && kill -0 "${ready_pid}" 2>/dev/null && xdg-open "${open_url}" && touch "${browser_marker}") &
    fi
  fi
  PORT="${ui_port}" BROWSER=none npm start >"${repo_dir}/frontend.log" 2>&1 &
  NPM_PID=$!
  echo "📋 Frontend logs → frontend.log  (tail -f frontend.log)"
}
