#!/bin/bash

# Generate the local VS Code debug configuration under .vscode/.
#
# Writes one CodeLLDB launch configuration per prepared local instance
# (envs/local, envs/local-<suffix>), an env file with the generated local
# development keys, the recommended-extensions list, and a settings.json that
# keeps the envs/docker tree out of search and the file
# watcher.
#
# Everything written here is gitignored and safe to regenerate. A file that was
# not produced by this script is left untouched and reported, so a hand-written
# launch.json is never clobbered.
#
# Usage: ./scripts/setup-vscode.sh

set -euo pipefail

source "$(dirname "$0")/_env.sh"

# Values the sourced helper above must provide.
: "${envs_dir:?_env.sh must set envs_dir}"
: "${local_env_dir:?_env.sh must set local_env_dir}"
: "${agent_name:?_env.sh must set agent_name}"

repo_dir="$(pwd)"
vscode_dir="${repo_dir}/.vscode"
marker="Generated by scripts/setup-vscode.sh"

# write_generated <path> <tmp_file>
# Moves <tmp_file> into place, refusing to overwrite a file that does not carry
# the generator marker.
write_generated() {
  local path="$1"
  local tmp="$2"
  if [[ -f "${path}" ]] && ! grep -q "${marker}" "${path}"; then
    echo "⚠️  Keeping hand-written ${path#"${repo_dir}"/} (no generator marker); new version at ${path#"${repo_dir}"/}.new"
    mv "${tmp}" "${path}.new"
    return 0
  fi
  mv "${tmp}" "${path}"
  echo "✅ ${path#"${repo_dir}"/}"
}

# Collect prepared instances: a directory is prepared once _prepare.sh has
# written its config/config.toml.
instances=()
for dir in "${local_env_dir}" "${local_env_dir}"-*; do
  [[ -f "${dir}/config/config.toml" ]] || continue
  instances+=("${dir}")
done

if [[ ${#instances[@]} -eq 0 ]]; then
  echo "❌ No prepared local instance found under ${envs_dir}."
  echo "   Run 'make config-debug' (or 'make config-debug-x x=<name>') first."
  exit 1
fi

mkdir -p "${vscode_dir}"

# ---------------------------------------------------------------------------
# launch.json — one CodeLLDB configuration per instance
# ---------------------------------------------------------------------------
launch_tmp="$(mktemp)"
{
  echo "{"
  echo "  \"//\": \"${marker} — regenerate with 'make setup-vscode'. Gitignored.\","
  echo "  \"version\": \"0.2.0\","
  echo "  \"configurations\": ["
  first=true
  for dir in "${instances[@]}"; do
    name="${dir#"${local_env_dir}"}"
    name="${name#-}"
    label="Agent Gateway${name:+ (${name})}"
    rel="${dir#"${repo_dir}"/}"
    ${first} || echo ","
    first=false
    cat <<EOF
    {
      "type": "lldb",
      "request": "launch",
      "name": "${label}",
      "cargo": {
        "args": ["build", "--bin=${agent_name}"],
        "filter": { "name": "${agent_name}", "kind": "bin" }
      },
      "args": ["--config", "config/config.toml"],
      "cwd": "\${workspaceFolder}/${rel}",
      "envFile": "\${workspaceFolder}/.vscode/${agent_name}.env",
      "sourceLanguages": ["rust"]
    }
EOF
  done
  echo ""
  echo "  ]"
  echo "}"
} >"${launch_tmp}"
write_generated "${vscode_dir}/launch.json" "${launch_tmp}"

# ---------------------------------------------------------------------------
# <agent_name>.env — generated local development keys
# ---------------------------------------------------------------------------
env_tmp="$(mktemp)"
cat >"${env_tmp}" <<EOF
# ${marker} — regenerate with 'make setup-vscode'. Gitignored.
# Local development keys only. Never reuse these values outside this machine.
RUST_LOG=${RUST_LOG:-debug}
RUST_BACKTRACE=1
AG_IDENTITY_HASH_PEPPER=${AG_IDENTITY_HASH_PEPPER}
AG_BACKUP_ENCRYPTION_KEY=${AG_BACKUP_ENCRYPTION_KEY}
EOF
write_generated "${vscode_dir}/${agent_name}.env" "${env_tmp}"

if [[ -z "${AG_IDENTITY_HASH_PEPPER}" || -z "${AG_BACKUP_ENCRYPTION_KEY}" ]]; then
  echo "⚠️  Identity pepper or backup key is empty — run 'make config-certs' to generate them."
fi

# An exported key wins over the generated local dev file (see _env.sh), so a real
# production secret in your environment would be written verbatim into a file
# labelled "local development keys only". Warn when the value did not come from
# the generated file so it can't leak under a false label.
pepper_file="${AG_IDENTITY_PEPPER_FILE:-${envs_dir}/identity_hash_pepper}"
backup_key_file="${AG_BACKUP_KEY_FILE:-${envs_dir}/backup_encryption_key}"
if { [[ -n "${AG_IDENTITY_HASH_PEPPER}" && -f "${pepper_file}" ]] && [[ "${AG_IDENTITY_HASH_PEPPER}" != "$(cat "${pepper_file}")" ]]; } ||
   { [[ -n "${AG_BACKUP_ENCRYPTION_KEY}" && -f "${backup_key_file}" ]] && [[ "${AG_BACKUP_ENCRYPTION_KEY}" != "$(cat "${backup_key_file}")" ]]; }; then
  echo "⚠️  A key written to ${agent_name}.env came from your environment, not the generated local dev file."
  echo "   Confirm it is NOT a production secret — this file is for local development only."
fi

# ---------------------------------------------------------------------------
# extensions.json — recommended extensions
# ---------------------------------------------------------------------------
ext_tmp="$(mktemp)"
cat >"${ext_tmp}" <<EOF
{
  "//": "${marker} — regenerate with 'make setup-vscode'. Gitignored.",
  "recommendations": [
    "rust-lang.rust-analyzer",
    "vadimcn.vscode-lldb"
  ]
}
EOF
write_generated "${vscode_dir}/extensions.json" "${ext_tmp}"

# ---------------------------------------------------------------------------
# settings.json — keep the envs/docker tree out of search
# and the file watcher
# ---------------------------------------------------------------------------
settings_tmp="$(mktemp)"
cat >"${settings_tmp}" <<EOF
{
  "//": "${marker} — regenerate with 'make setup-vscode'. Gitignored.",
  "search.exclude": {
    "envs/docker/**": true
  },
  "files.watcherExclude": {
    "envs/docker/**": true
  }
}
EOF
write_generated "${vscode_dir}/settings.json" "${settings_tmp}"

echo ""
echo "VS Code debug setup ready for ${#instances[@]} instance(s):"
for dir in "${instances[@]}"; do
  echo "  • ${dir#"${repo_dir}"/}"
done
echo ""
echo "Install the recommended extensions, press F5, and pick an Agent Gateway configuration."
echo "F5 debugs the backend only — use 'make run-debug' when you also need the frontend dev server."
